<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit469500b18f9ff456247e45b98a5ea8f0
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit469500b18f9ff456247e45b98a5ea8f0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit469500b18f9ff456247e45b98a5ea8f0::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
